pipeline:
  name: test_build_and_publish_early_access_pypi
  identifier: test_build_and_publish_early_access_pypi
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - stage:
        name: Publish to TestPypi
        identifier: Publish_to_TestPypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
