pipeline:
  name: test-release-early-access-pypi
  identifier: test_build_and_publish_early_access_pypi
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - stage:
        name: Lint
        identifier: Lint
        template:
          templateRef: Lint_Repo
          versionLabel: "1"
    - stage:
        name: Publish to TestPypi
        identifier: Publish_to_TestPypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
          templateInputs:
            type: CI
            variables:
              - name: BUILD_TYPE
                type: String
                default: test-early-access
                value: test-early-access
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
