pipeline:
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - stage:
        name: Lint
        identifier: Lint
        template:
          templateRef: Lint_Repo
          versionLabel: "1"
    - stage:
        name: Publish Release to TestPypi
        identifier: Publish_Release_to_TestPypi
        template:
          templateRef: Publish_to_Pypi_or_TestPypi
          versionLabel: "1"
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
  identifier: releasepypi
  name: release-pypi
