pipeline:
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - stage:
        name: Publish to Pypi
        identifier: Publish_to_Pypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
          templateInputs:
            type: CI
            variables:
              - name: BUILD_TYPE
                type: String
                default: test
                value: pypi
  identifier: releaseearlyaccesspypi
  name: release-early-access-pypi
