pipeline:
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - parallel:
        - stage:
            name: Lint
            identifier: Lint
            template:
              templateRef: Lint_Repo
              versionLabel: "1"
        - stage:
            name: Unit Tests
            identifier: Unit_Tests
            template:
              templateRef: unit_tests
              versionLabel: "1"
    - stage:
        name: Release to Github
        identifier: Release_to_Github
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Release to Github
                  identifier: Release_to_Github
                  spec:
                    shell: Sh
                    command: |-
                      set -ex pipefail
                      # Install github-cli
                      curl -sS https://webi.sh/gh | sh

                      # Clone the repo
                      git clone https://github.com/datarobot/airflow-provider-datarobot.git
                      cd airflow-provider-datarobot

                      # Create a standard release
                      gh release create $RELEASE_VERSION --latest=true --title "$RELEASE_VERSION" --generate-notes
        variables:
          - name: RELEASE_VERSION
            type: String
            description: |-
              Please provide the version to use for the release. This version should include the `v` prefix.

              Example:
              v1.0.0
            required: true
            value: <+input>
    - stage:
        name: Publish to Test Pypi
        identifier: Publish_to_Test_Pypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
          templateInputs:
            type: CI
            variables:
              - name: BUILD_TYPE
                type: String
                default: release-early-access-test-pypi
                value: release-early-access-test-pypi
    - stage:
        name: Publish to Pypi
        identifier: Publish_to_Pypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
          templateInputs:
            type: CI
            variables:
              - name: BUILD_TYPE
                type: String
                default: release-early-access-test-pypi
                value: release-early-access-pypi
  identifier: releaseearlyaccesspypi
  name: release-early-access-pypi
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
