pipeline:
  projectIdentifier: airflowproviderdatarobot
  orgIdentifier: AGENTS
  tags: {}
  stages:
    - stage:
        name: Lint
        identifier: Lint
        template:
          templateRef: Lint_Repo
          versionLabel: "1"
    - stage:
        name: Publish to Pypi
        identifier: Publish_to_Pypi
        template:
          templateRef: publish_early_access_to_pypi_or_testpypi
          versionLabel: "1"
          templateInputs:
            type: CI
            variables:
              - name: BUILD_TYPE
                type: String
                default: test-early-access
                value: early-access
  identifier: releaseearlyaccesspypi
  name: release-early-access-pypi
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
