pipeline:
  name: build-and-publish-pip-early-access
  identifier: buildandpublishpipearlyaccess
  projectIdentifier: dummy
  orgIdentifier: AGENTS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: black
            identifier: black
            description: ""
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: pip install step
                      identifier: Run_Pip
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.9
                        shell: Bash
                        command: |-
                          set -exuo pipefail
                          pip install -U pip
                          pip install --upgrade pip wheel setuptools
                          pip install -r requirements.txt
                          pip install --upgrade build twine
                          echo "Building wheel..."
                          python -m build --no-isolation
                          echo "Building wheel...OK"
                          echo $(ls)
                  - step:
                      type: Run
                      name: publish pip step
                      identifier: Run_Publish
                      spec:
                        envVariables:
                          PYPI_TOKEN: <+secrets.getValue("test-secret")>
                          PYPI_TOKEN2: test-variable
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.9
                        shell: Bash
                        command: |-
                          set -exuo pipefail
                          echo "Publishing wheel to pip..."
                          echo $(ls)
                          echo "$PYPI_TOKEN"
