pipeline:
  name: build-and-publish-pip-early-access
  identifier: buildandpublishpipearlyaccess
  projectIdentifier: dummy
  orgIdentifier: AGENTS
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: airflow-provider-datarobot
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: black
            identifier: black
            description: ""
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.cigeneral
                  namespace: harness-delegate-ng
                  automountServiceAccountToken: true
                  nodeSelector: {}
                  os: Linux
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: black check step
                      identifier: Run_1
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.9
                        shell: Bash
                        command: |-
                          set -exuo pipefail
                          pip install -U pip
                          pip install -r requirements.txt
                          pip install pylint
                          make lint
